name: fmalign2x
channels:
  - bioconda
  - conda-forge
dependencies:
  - gcc=14
  - gxx=14
  - cmake
  - make
  - binutils
  - ld_impl_linux-64
  - libgcc-devel_linux-64
  - libstdcxx-devel_linux-64
  - sysroot_linux-64
  - openmp
  - git
  - curl
  - wget
  - pkg-config
  - python
  - seqkit
  - pip
  - pip:
      - pymsa
