name: fmalign2x
channels:
  - conda-forge
  - bioconda
dependencies:
  - gcc=14
  - gxx=14
  - cmake
  - make
  - binutils
  - ld_impl_linux-64
  - libgcc-devel_linux-64
  - libstdcxx-devel_linux-64
  - sysroot_linux-64
  - openmp
  - seqkit
  - git
  - curl
  - wget
  - python
  - pip